### ISSUE TITLE
Error when updating an Appointment

### ISSUE THREAD

**Issue by BBS007** [BBS007/DoctorZZ#11]
First, create an appointment :

```bash
curl -X POST localhost:8080/DoctorZZ/ws/patient/1/appointment/1
````

Give the following in the browser

```xml
<appointments>
    <appointment>
    <id>9</id>
    <patient>
        <id>1</id>
        <name>Barbesange</name>
        <surname>Benjamin</surname>
    </patient>
    <schedule>
        <doctor>
            <id>1</id>
            <name>House</name>
            <surname>Gregory</surname>
        </doctor>
        <endDate>2017-03-30T00:00:00+02:00</endDate>
        <id>1</id>
        <startDate>2017-03-30T00:00:00+02:00</startDate>
    </schedule>
</appointment>
</appointments>
```

Then i want to change the schedule

```bash
curl -i -H "Content-Type: application/json" -X PUT localhost:8080/DoctorZZ/ws/patient/appointment/9 -d '{"patient": {"id":1}, "schedule":{"id":2}}'
```

And i have a doctor out of nowhere

```xml
<appointments>
    <appointment>
    <id>9</id>
    <patient>
        <id>1</id>
        <name>Barbesange</name>
        <surname>Benjamin</surname>
    </patient>
    <schedule>
        <doctor>
            <id>10</id>
            <name/>
            <surname/>
        </doctor>
        <endDate>2017-03-30T00:00:00+02:00</endDate>
        <id>2</id>
        <startDate>2017-03-30T00:00:00+02:00</startDate>
    </schedule>
    </appointment>
</appointments>
```

I don't know why a doctor is created ...

**Comment by theCmaker** [comment]
Was the schedule 2 created ?
If it wasn't, that may be the reason. We should check that the data exists. (The manager creates it when it does not...)

**Comment by BBS007** [comment]
There is schedule with id n°2.

But i tried again and this time when i try to change schedule, it throws an error saying Duplicate primary key id (the one for the schedule) but trying to create a Doctor ...

![image](https://cloud.githubusercontent.com/assets/3964808/24496549/d810f036-1538-11e7-8da8-acf7d650f049.png)

When i change the schedule id the the json request, it keeps telling me that for a doctor

**Comment by theCmaker** [comment]
Oh snap... That is strange. I'm trying to do it again on my server.
Was the DB empty when you started the server?

**Comment by BBS007** [comment]
Each time i redeploy, my db is empty, i fill it with the data in the script.

I don't knwo where is that problem. I checked the binding, cascade, seems fine.
But i don't understand how the editAppointment() works

```java
@PUT
@Path("appointment/{id}")
@Consumes({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
public void editAppointment(@PathParam("id") Integer id, Appointment new_appointment) {
    new_appointment.setId(id.longValue());
    appointmentManager.updateAppointment(new_appointment);
}
```

How is it knowing which schedule and patient to treat, is it automaticly performing getPatient(id) and getSchedule(id) ?
Because that might be the problem...

**Comment by theCmaker** [comment]
That should not. Just have a look at AppointmentManager::updateAppointment(). There is a check. But I think a part of the manager is wrong. I think it is near some get<Entity>. For doctor and patient, an empty instance is return. Thus it should be null. I am fixing it.
