### ISSUE TITLE
Deploy.sh

### ISSUE THREAD

**Issue by BBS007** [BBS007/DoctorZZ#4]
- [x] Install packages
- [x] Config MySql
- [x] Config payara
- [x] Deploy
- [x] Stop

**Comment by BBS007** [comment]
The MySQL config is basically connecting as root and running create_database.sql.

The payara config need to set the pool for the database.

The deployment is made using the final .war

**Comment by theCmaker** [comment]
I opened a new branch on which I added the webservices I developped (integration in Netbeans, including Payara as a server in Netbeans).

A Payara config as-admin file is provided in scripts directory.

**Comment by BBS007** [comment]
Needing test

**Comment by theCmaker** [comment]
Payara as-admin script added on branch master.

**Comment by BBS007** [comment]
For apt-get install remove '-d' option

**Comment by theCmaker** [comment]
Done in ec7bbcd

**Comment by BBS007** [comment]
The war deployment doesn't seem to work. @theCmaker please copy the final war in scripts/ and rename it DoctorZZ.war.
